# Generated by Django 4.2.4 on 2023-08-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formfiller", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "package_interested",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("thunder", "Thunder"),
                            ("storm", "Storm"),
                            ("flash", "Flash"),
                            ("void", "Void"),
                        ],
                        max_length=10,
                    ),
                ),
                ("home_address", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=15)),
            ],
        ),
    ]
